name: Elasticsearch Docker Image CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Build the Elasticsearch Docker image
      run: docker build elasticsearch
